package com.yunwei.wetlandpark.greedao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CHECKING_FORM".
 */
public class CheckingForm {

    private Integer RecordType;
    private String TaskId;
    private String TaskPointTid;
    private String Remark;
    private Integer Status;
    private String Reason;
    private String Result;
    private String FacilityCode;
    private String Address;
    private Double X;
    private Double Y;
    private Double Z;
    private Double Lng;
    private Double Lat;
    private String AttrJson;
    private String ImagesUrl;
    private Long saveTime;

    public CheckingForm() {
    }

    public CheckingForm(Integer RecordType, String TaskId, String TaskPointTid, String Remark, Integer Status, String Reason, String Result, String FacilityCode, String Address, Double X, Double Y, Double Z, Double Lng, Double Lat, String AttrJson, String ImagesUrl, Long saveTime) {
        this.RecordType = RecordType;
        this.TaskId = TaskId;
        this.TaskPointTid = TaskPointTid;
        this.Remark = Remark;
        this.Status = Status;
        this.Reason = Reason;
        this.Result = Result;
        this.FacilityCode = FacilityCode;
        this.Address = Address;
        this.X = X;
        this.Y = Y;
        this.Z = Z;
        this.Lng = Lng;
        this.Lat = Lat;
        this.AttrJson = AttrJson;
        this.ImagesUrl = ImagesUrl;
        this.saveTime = saveTime;
    }

    public Integer getRecordType() {
        return RecordType;
    }

    public void setRecordType(Integer RecordType) {
        this.RecordType = RecordType;
    }

    public String getTaskId() {
        return TaskId;
    }

    public void setTaskId(String TaskId) {
        this.TaskId = TaskId;
    }

    public String getTaskPointTid() {
        return TaskPointTid;
    }

    public void setTaskPointTid(String TaskPointTid) {
        this.TaskPointTid = TaskPointTid;
    }

    public String getRemark() {
        return Remark;
    }

    public void setRemark(String Remark) {
        this.Remark = Remark;
    }

    public Integer getStatus() {
        return Status;
    }

    public void setStatus(Integer Status) {
        this.Status = Status;
    }

    public String getReason() {
        return Reason;
    }

    public void setReason(String Reason) {
        this.Reason = Reason;
    }

    public String getResult() {
        return Result;
    }

    public void setResult(String Result) {
        this.Result = Result;
    }

    public String getFacilityCode() {
        return FacilityCode;
    }

    public void setFacilityCode(String FacilityCode) {
        this.FacilityCode = FacilityCode;
    }

    public String getAddress() {
        return Address;
    }

    public void setAddress(String Address) {
        this.Address = Address;
    }

    public Double getX() {
        return X;
    }

    public void setX(Double X) {
        this.X = X;
    }

    public Double getY() {
        return Y;
    }

    public void setY(Double Y) {
        this.Y = Y;
    }

    public Double getZ() {
        return Z;
    }

    public void setZ(Double Z) {
        this.Z = Z;
    }

    public Double getLng() {
        return Lng;
    }

    public void setLng(Double Lng) {
        this.Lng = Lng;
    }

    public Double getLat() {
        return Lat;
    }

    public void setLat(Double Lat) {
        this.Lat = Lat;
    }

    public String getAttrJson() {
        return AttrJson;
    }

    public void setAttrJson(String AttrJson) {
        this.AttrJson = AttrJson;
    }

    public String getImagesUrl() {
        return ImagesUrl;
    }

    public void setImagesUrl(String ImagesUrl) {
        this.ImagesUrl = ImagesUrl;
    }

    public Long getSaveTime() {
        return saveTime;
    }

    public void setSaveTime(Long saveTime) {
        this.saveTime = saveTime;
    }

}
