package com.yunwei.wetlandpark.greedao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CHECK_PLAN_TABLE".
 */
public class CheckPlanTable implements java.io.Serializable {

    private Long id;
    private String planID;
    private String date;
    private String startAt;
    private String endAt;
    private String firstSecondRoomTemp;
    private String firstSecondRoomHum;
    private String thirdRoomTemp;
    private String thirdRoomHum;
    private String firefightingSystem;
    private String usbRoom;
    private String airConditioner;
    private String compensationMeter;
    private String distributionRoom;
    private String coreRouter;
    private String accessSystem;
    private String note;
    private String checkedPointCount;
    private String checkedUser;

    public CheckPlanTable() {
    }

    public CheckPlanTable(Long id) {
        this.id = id;
    }

    public CheckPlanTable(Long id, String planID, String date, String startAt, String endAt, String firstSecondRoomTemp, String firstSecondRoomHum, String thirdRoomTemp, String thirdRoomHum, String firefightingSystem, String usbRoom, String airConditioner, String compensationMeter, String distributionRoom, String coreRouter, String accessSystem, String note, String checkedPointCount, String checkedUser) {
        this.id = id;
        this.planID = planID;
        this.date = date;
        this.startAt = startAt;
        this.endAt = endAt;
        this.firstSecondRoomTemp = firstSecondRoomTemp;
        this.firstSecondRoomHum = firstSecondRoomHum;
        this.thirdRoomTemp = thirdRoomTemp;
        this.thirdRoomHum = thirdRoomHum;
        this.firefightingSystem = firefightingSystem;
        this.usbRoom = usbRoom;
        this.airConditioner = airConditioner;
        this.compensationMeter = compensationMeter;
        this.distributionRoom = distributionRoom;
        this.coreRouter = coreRouter;
        this.accessSystem = accessSystem;
        this.note = note;
        this.checkedPointCount = checkedPointCount;
        this.checkedUser = checkedUser;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPlanID() {
        return planID;
    }

    public void setPlanID(String planID) {
        this.planID = planID;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getStartAt() {
        return startAt;
    }

    public void setStartAt(String startAt) {
        this.startAt = startAt;
    }

    public String getEndAt() {
        return endAt;
    }

    public void setEndAt(String endAt) {
        this.endAt = endAt;
    }

    public String getFirstSecondRoomTemp() {
        return firstSecondRoomTemp;
    }

    public void setFirstSecondRoomTemp(String firstSecondRoomTemp) {
        this.firstSecondRoomTemp = firstSecondRoomTemp;
    }

    public String getFirstSecondRoomHum() {
        return firstSecondRoomHum;
    }

    public void setFirstSecondRoomHum(String firstSecondRoomHum) {
        this.firstSecondRoomHum = firstSecondRoomHum;
    }

    public String getThirdRoomTemp() {
        return thirdRoomTemp;
    }

    public void setThirdRoomTemp(String thirdRoomTemp) {
        this.thirdRoomTemp = thirdRoomTemp;
    }

    public String getThirdRoomHum() {
        return thirdRoomHum;
    }

    public void setThirdRoomHum(String thirdRoomHum) {
        this.thirdRoomHum = thirdRoomHum;
    }

    public String getFirefightingSystem() {
        return firefightingSystem;
    }

    public void setFirefightingSystem(String firefightingSystem) {
        this.firefightingSystem = firefightingSystem;
    }

    public String getUsbRoom() {
        return usbRoom;
    }

    public void setUsbRoom(String usbRoom) {
        this.usbRoom = usbRoom;
    }

    public String getAirConditioner() {
        return airConditioner;
    }

    public void setAirConditioner(String airConditioner) {
        this.airConditioner = airConditioner;
    }

    public String getCompensationMeter() {
        return compensationMeter;
    }

    public void setCompensationMeter(String compensationMeter) {
        this.compensationMeter = compensationMeter;
    }

    public String getDistributionRoom() {
        return distributionRoom;
    }

    public void setDistributionRoom(String distributionRoom) {
        this.distributionRoom = distributionRoom;
    }

    public String getCoreRouter() {
        return coreRouter;
    }

    public void setCoreRouter(String coreRouter) {
        this.coreRouter = coreRouter;
    }

    public String getAccessSystem() {
        return accessSystem;
    }

    public void setAccessSystem(String accessSystem) {
        this.accessSystem = accessSystem;
    }

    public String getNote() {
        return note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    public String getCheckedPointCount() {
        return checkedPointCount;
    }

    public void setCheckedPointCount(String checkedPointCount) {
        this.checkedPointCount = checkedPointCount;
    }

    public String getCheckedUser() {
        return checkedUser;
    }

    public void setCheckedUser(String checkedUser) {
        this.checkedUser = checkedUser;
    }

}
