package com.yunwei.wetlandpark.greedao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CHECK_DEVICE_TABLE".
 */
public class CheckDeviceTable implements java.io.Serializable {

    private Long id;
    private String deviceID;
    private String deviceCode;
    private String deviceAddress;
    private Integer deviceTypeCode;
    private String deviceTypeName;
    private String userName;
    private String userID;
    private String hdType;
    private String hdDesc;
    private Integer deviceStatus;
    private Double lng;
    private Double lat;
    private String workAddress;
    private Long saveTime;
    private String note;
    private String reportType;
    private String imagesUrl;
    private Integer localTag;
    private String missionID;
    private String missionPointID;

    public CheckDeviceTable() {
    }

    public CheckDeviceTable(Long id) {
        this.id = id;
    }

    public CheckDeviceTable(Long id, String deviceID, String deviceCode, String deviceAddress, Integer deviceTypeCode, String deviceTypeName, String userName, String userID, String hdType, String hdDesc, Integer deviceStatus, Double lng, Double lat, String workAddress, Long saveTime, String note, String reportType, String imagesUrl, Integer localTag, String missionID, String missionPointID) {
        this.id = id;
        this.deviceID = deviceID;
        this.deviceCode = deviceCode;
        this.deviceAddress = deviceAddress;
        this.deviceTypeCode = deviceTypeCode;
        this.deviceTypeName = deviceTypeName;
        this.userName = userName;
        this.userID = userID;
        this.hdType = hdType;
        this.hdDesc = hdDesc;
        this.deviceStatus = deviceStatus;
        this.lng = lng;
        this.lat = lat;
        this.workAddress = workAddress;
        this.saveTime = saveTime;
        this.note = note;
        this.reportType = reportType;
        this.imagesUrl = imagesUrl;
        this.localTag = localTag;
        this.missionID = missionID;
        this.missionPointID = missionPointID;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDeviceID() {
        return deviceID;
    }

    public void setDeviceID(String deviceID) {
        this.deviceID = deviceID;
    }

    public String getDeviceCode() {
        return deviceCode;
    }

    public void setDeviceCode(String deviceCode) {
        this.deviceCode = deviceCode;
    }

    public String getDeviceAddress() {
        return deviceAddress;
    }

    public void setDeviceAddress(String deviceAddress) {
        this.deviceAddress = deviceAddress;
    }

    public Integer getDeviceTypeCode() {
        return deviceTypeCode;
    }

    public void setDeviceTypeCode(Integer deviceTypeCode) {
        this.deviceTypeCode = deviceTypeCode;
    }

    public String getDeviceTypeName() {
        return deviceTypeName;
    }

    public void setDeviceTypeName(String deviceTypeName) {
        this.deviceTypeName = deviceTypeName;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getUserID() {
        return userID;
    }

    public void setUserID(String userID) {
        this.userID = userID;
    }

    public String getHdType() {
        return hdType;
    }

    public void setHdType(String hdType) {
        this.hdType = hdType;
    }

    public String getHdDesc() {
        return hdDesc;
    }

    public void setHdDesc(String hdDesc) {
        this.hdDesc = hdDesc;
    }

    public Integer getDeviceStatus() {
        return deviceStatus;
    }

    public void setDeviceStatus(Integer deviceStatus) {
        this.deviceStatus = deviceStatus;
    }

    public Double getLng() {
        return lng;
    }

    public void setLng(Double lng) {
        this.lng = lng;
    }

    public Double getLat() {
        return lat;
    }

    public void setLat(Double lat) {
        this.lat = lat;
    }

    public String getWorkAddress() {
        return workAddress;
    }

    public void setWorkAddress(String workAddress) {
        this.workAddress = workAddress;
    }

    public Long getSaveTime() {
        return saveTime;
    }

    public void setSaveTime(Long saveTime) {
        this.saveTime = saveTime;
    }

    public String getNote() {
        return note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    public String getReportType() {
        return reportType;
    }

    public void setReportType(String reportType) {
        this.reportType = reportType;
    }

    public String getImagesUrl() {
        return imagesUrl;
    }

    public void setImagesUrl(String imagesUrl) {
        this.imagesUrl = imagesUrl;
    }

    public Integer getLocalTag() {
        return localTag;
    }

    public void setLocalTag(Integer localTag) {
        this.localTag = localTag;
    }

    public String getMissionID() {
        return missionID;
    }

    public void setMissionID(String missionID) {
        this.missionID = missionID;
    }

    public String getMissionPointID() {
        return missionPointID;
    }

    public void setMissionPointID(String missionPointID) {
        this.missionPointID = missionPointID;
    }

}
