package com.yunwei.wetlandpark.greedao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.yunwei.wetlandpark.greedao.Track;
import com.yunwei.wetlandpark.greedao.TrackPoint;
import com.yunwei.wetlandpark.greedao.TrackPointsTable;
import com.yunwei.wetlandpark.greedao.DeviceTable;
import com.yunwei.wetlandpark.greedao.CheckPlanTable;
import com.yunwei.wetlandpark.greedao.MaintainDeviceTable;
import com.yunwei.wetlandpark.greedao.TaskListAndDetailEntity;
import com.yunwei.wetlandpark.greedao.TaskPointListEntity;
import com.yunwei.wetlandpark.greedao.PlanToInspectEntity;
import com.yunwei.wetlandpark.greedao.TroubleTable;
import com.yunwei.wetlandpark.greedao.TroubleShooterTable;
import com.yunwei.wetlandpark.greedao.SignInTable;

import com.yunwei.wetlandpark.greedao.TrackDao;
import com.yunwei.wetlandpark.greedao.TrackPointDao;
import com.yunwei.wetlandpark.greedao.TrackPointsTableDao;
import com.yunwei.wetlandpark.greedao.DeviceTableDao;
import com.yunwei.wetlandpark.greedao.CheckPlanTableDao;
import com.yunwei.wetlandpark.greedao.MaintainDeviceTableDao;
import com.yunwei.wetlandpark.greedao.TaskListAndDetailEntityDao;
import com.yunwei.wetlandpark.greedao.TaskPointListEntityDao;
import com.yunwei.wetlandpark.greedao.PlanToInspectEntityDao;
import com.yunwei.wetlandpark.greedao.TroubleTableDao;
import com.yunwei.wetlandpark.greedao.TroubleShooterTableDao;
import com.yunwei.wetlandpark.greedao.SignInTableDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig trackDaoConfig;
    private final DaoConfig trackPointDaoConfig;
    private final DaoConfig trackPointsTableDaoConfig;
    private final DaoConfig deviceTableDaoConfig;
    private final DaoConfig checkPlanTableDaoConfig;
    private final DaoConfig maintainDeviceTableDaoConfig;
    private final DaoConfig taskListAndDetailEntityDaoConfig;
    private final DaoConfig taskPointListEntityDaoConfig;
    private final DaoConfig planToInspectEntityDaoConfig;
    private final DaoConfig troubleTableDaoConfig;
    private final DaoConfig troubleShooterTableDaoConfig;
    private final DaoConfig signInTableDaoConfig;

    private final TrackDao trackDao;
    private final TrackPointDao trackPointDao;
    private final TrackPointsTableDao trackPointsTableDao;
    private final DeviceTableDao deviceTableDao;
    private final CheckPlanTableDao checkPlanTableDao;
    private final MaintainDeviceTableDao maintainDeviceTableDao;
    private final TaskListAndDetailEntityDao taskListAndDetailEntityDao;
    private final TaskPointListEntityDao taskPointListEntityDao;
    private final PlanToInspectEntityDao planToInspectEntityDao;
    private final TroubleTableDao troubleTableDao;
    private final TroubleShooterTableDao troubleShooterTableDao;
    private final SignInTableDao signInTableDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        trackDaoConfig = daoConfigMap.get(TrackDao.class).clone();
        trackDaoConfig.initIdentityScope(type);

        trackPointDaoConfig = daoConfigMap.get(TrackPointDao.class).clone();
        trackPointDaoConfig.initIdentityScope(type);

        trackPointsTableDaoConfig = daoConfigMap.get(TrackPointsTableDao.class).clone();
        trackPointsTableDaoConfig.initIdentityScope(type);

        deviceTableDaoConfig = daoConfigMap.get(DeviceTableDao.class).clone();
        deviceTableDaoConfig.initIdentityScope(type);

        checkPlanTableDaoConfig = daoConfigMap.get(CheckPlanTableDao.class).clone();
        checkPlanTableDaoConfig.initIdentityScope(type);

        maintainDeviceTableDaoConfig = daoConfigMap.get(MaintainDeviceTableDao.class).clone();
        maintainDeviceTableDaoConfig.initIdentityScope(type);

        taskListAndDetailEntityDaoConfig = daoConfigMap.get(TaskListAndDetailEntityDao.class).clone();
        taskListAndDetailEntityDaoConfig.initIdentityScope(type);

        taskPointListEntityDaoConfig = daoConfigMap.get(TaskPointListEntityDao.class).clone();
        taskPointListEntityDaoConfig.initIdentityScope(type);

        planToInspectEntityDaoConfig = daoConfigMap.get(PlanToInspectEntityDao.class).clone();
        planToInspectEntityDaoConfig.initIdentityScope(type);

        troubleTableDaoConfig = daoConfigMap.get(TroubleTableDao.class).clone();
        troubleTableDaoConfig.initIdentityScope(type);

        troubleShooterTableDaoConfig = daoConfigMap.get(TroubleShooterTableDao.class).clone();
        troubleShooterTableDaoConfig.initIdentityScope(type);

        signInTableDaoConfig = daoConfigMap.get(SignInTableDao.class).clone();
        signInTableDaoConfig.initIdentityScope(type);

        trackDao = new TrackDao(trackDaoConfig, this);
        trackPointDao = new TrackPointDao(trackPointDaoConfig, this);
        trackPointsTableDao = new TrackPointsTableDao(trackPointsTableDaoConfig, this);
        deviceTableDao = new DeviceTableDao(deviceTableDaoConfig, this);
        checkPlanTableDao = new CheckPlanTableDao(checkPlanTableDaoConfig, this);
        maintainDeviceTableDao = new MaintainDeviceTableDao(maintainDeviceTableDaoConfig, this);
        taskListAndDetailEntityDao = new TaskListAndDetailEntityDao(taskListAndDetailEntityDaoConfig, this);
        taskPointListEntityDao = new TaskPointListEntityDao(taskPointListEntityDaoConfig, this);
        planToInspectEntityDao = new PlanToInspectEntityDao(planToInspectEntityDaoConfig, this);
        troubleTableDao = new TroubleTableDao(troubleTableDaoConfig, this);
        troubleShooterTableDao = new TroubleShooterTableDao(troubleShooterTableDaoConfig, this);
        signInTableDao = new SignInTableDao(signInTableDaoConfig, this);

        registerDao(Track.class, trackDao);
        registerDao(TrackPoint.class, trackPointDao);
        registerDao(TrackPointsTable.class, trackPointsTableDao);
        registerDao(DeviceTable.class, deviceTableDao);
        registerDao(CheckPlanTable.class, checkPlanTableDao);
        registerDao(MaintainDeviceTable.class, maintainDeviceTableDao);
        registerDao(TaskListAndDetailEntity.class, taskListAndDetailEntityDao);
        registerDao(TaskPointListEntity.class, taskPointListEntityDao);
        registerDao(PlanToInspectEntity.class, planToInspectEntityDao);
        registerDao(TroubleTable.class, troubleTableDao);
        registerDao(TroubleShooterTable.class, troubleShooterTableDao);
        registerDao(SignInTable.class, signInTableDao);
    }
    
    public void clear() {
        trackDaoConfig.getIdentityScope().clear();
        trackPointDaoConfig.getIdentityScope().clear();
        trackPointsTableDaoConfig.getIdentityScope().clear();
        deviceTableDaoConfig.getIdentityScope().clear();
        checkPlanTableDaoConfig.getIdentityScope().clear();
        maintainDeviceTableDaoConfig.getIdentityScope().clear();
        taskListAndDetailEntityDaoConfig.getIdentityScope().clear();
        taskPointListEntityDaoConfig.getIdentityScope().clear();
        planToInspectEntityDaoConfig.getIdentityScope().clear();
        troubleTableDaoConfig.getIdentityScope().clear();
        troubleShooterTableDaoConfig.getIdentityScope().clear();
        signInTableDaoConfig.getIdentityScope().clear();
    }

    public TrackDao getTrackDao() {
        return trackDao;
    }

    public TrackPointDao getTrackPointDao() {
        return trackPointDao;
    }

    public TrackPointsTableDao getTrackPointsTableDao() {
        return trackPointsTableDao;
    }

    public DeviceTableDao getDeviceTableDao() {
        return deviceTableDao;
    }

    public CheckPlanTableDao getCheckPlanTableDao() {
        return checkPlanTableDao;
    }

    public MaintainDeviceTableDao getMaintainDeviceTableDao() {
        return maintainDeviceTableDao;
    }

    public TaskListAndDetailEntityDao getTaskListAndDetailEntityDao() {
        return taskListAndDetailEntityDao;
    }

    public TaskPointListEntityDao getTaskPointListEntityDao() {
        return taskPointListEntityDao;
    }

    public PlanToInspectEntityDao getPlanToInspectEntityDao() {
        return planToInspectEntityDao;
    }

    public TroubleTableDao getTroubleTableDao() {
        return troubleTableDao;
    }

    public TroubleShooterTableDao getTroubleShooterTableDao() {
        return troubleShooterTableDao;
    }

    public SignInTableDao getSignInTableDao() {
        return signInTableDao;
    }

}
