package com.yunwei.wetlandpark.greedao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "FACILITY".
 */
public class Facility implements java.io.Serializable {

    private Long id;
    private String guid;
    private String code;
    private String address;
    private String oldCode;
    private String category;
    /** Not-null value. */
    private String type;
    private String createTime;
    private Integer userID;
    private String userName;
    private Integer unitID;
    private Double x;
    private Double y;
    private String addrCode;
    private String lampCode;
    private String ownerPolice;
    private String monitorCode;
    private String owner;
    private String ownerOffice;
    private String description;
    private Integer height;
    private Integer zoneID;
    private String zoneName;
    private String remark;
    private String images;
    private String status;
    private Integer state;
    private Integer objectID;
    private Integer pointId;
    private String taskId;
    private String taskPointId;
    private String hdType;
    private String hdDesc;
    private Integer revInt1;
    private Integer revInt2;
    private String revString1;
    private String revString2;

    public Facility() {
    }

    public Facility(Long id) {
        this.id = id;
    }

    public Facility(Long id, String guid, String code, String address, String oldCode, String category, String type, String createTime, Integer userID, String userName, Integer unitID, Double x, Double y, String addrCode, String lampCode, String ownerPolice, String monitorCode, String owner, String ownerOffice, String description, Integer height, Integer zoneID, String zoneName, String remark, String images, String status, Integer state, Integer objectID, Integer pointId, String taskId, String taskPointId, String hdType, String hdDesc, Integer revInt1, Integer revInt2, String revString1, String revString2) {
        this.id = id;
        this.guid = guid;
        this.code = code;
        this.address = address;
        this.oldCode = oldCode;
        this.category = category;
        this.type = type;
        this.createTime = createTime;
        this.userID = userID;
        this.userName = userName;
        this.unitID = unitID;
        this.x = x;
        this.y = y;
        this.addrCode = addrCode;
        this.lampCode = lampCode;
        this.ownerPolice = ownerPolice;
        this.monitorCode = monitorCode;
        this.owner = owner;
        this.ownerOffice = ownerOffice;
        this.description = description;
        this.height = height;
        this.zoneID = zoneID;
        this.zoneName = zoneName;
        this.remark = remark;
        this.images = images;
        this.status = status;
        this.state = state;
        this.objectID = objectID;
        this.pointId = pointId;
        this.taskId = taskId;
        this.taskPointId = taskPointId;
        this.hdType = hdType;
        this.hdDesc = hdDesc;
        this.revInt1 = revInt1;
        this.revInt2 = revInt2;
        this.revString1 = revString1;
        this.revString2 = revString2;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getGuid() {
        return guid;
    }

    public void setGuid(String guid) {
        this.guid = guid;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getOldCode() {
        return oldCode;
    }

    public void setOldCode(String oldCode) {
        this.oldCode = oldCode;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    /** Not-null value. */
    public String getType() {
        return type;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setType(String type) {
        this.type = type;
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    public Integer getUserID() {
        return userID;
    }

    public void setUserID(Integer userID) {
        this.userID = userID;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public Integer getUnitID() {
        return unitID;
    }

    public void setUnitID(Integer unitID) {
        this.unitID = unitID;
    }

    public Double getX() {
        return x;
    }

    public void setX(Double x) {
        this.x = x;
    }

    public Double getY() {
        return y;
    }

    public void setY(Double y) {
        this.y = y;
    }

    public String getAddrCode() {
        return addrCode;
    }

    public void setAddrCode(String addrCode) {
        this.addrCode = addrCode;
    }

    public String getLampCode() {
        return lampCode;
    }

    public void setLampCode(String lampCode) {
        this.lampCode = lampCode;
    }

    public String getOwnerPolice() {
        return ownerPolice;
    }

    public void setOwnerPolice(String ownerPolice) {
        this.ownerPolice = ownerPolice;
    }

    public String getMonitorCode() {
        return monitorCode;
    }

    public void setMonitorCode(String monitorCode) {
        this.monitorCode = monitorCode;
    }

    public String getOwner() {
        return owner;
    }

    public void setOwner(String owner) {
        this.owner = owner;
    }

    public String getOwnerOffice() {
        return ownerOffice;
    }

    public void setOwnerOffice(String ownerOffice) {
        this.ownerOffice = ownerOffice;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Integer getHeight() {
        return height;
    }

    public void setHeight(Integer height) {
        this.height = height;
    }

    public Integer getZoneID() {
        return zoneID;
    }

    public void setZoneID(Integer zoneID) {
        this.zoneID = zoneID;
    }

    public String getZoneName() {
        return zoneName;
    }

    public void setZoneName(String zoneName) {
        this.zoneName = zoneName;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getImages() {
        return images;
    }

    public void setImages(String images) {
        this.images = images;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    public Integer getObjectID() {
        return objectID;
    }

    public void setObjectID(Integer objectID) {
        this.objectID = objectID;
    }

    public Integer getPointId() {
        return pointId;
    }

    public void setPointId(Integer pointId) {
        this.pointId = pointId;
    }

    public String getTaskId() {
        return taskId;
    }

    public void setTaskId(String taskId) {
        this.taskId = taskId;
    }

    public String getTaskPointId() {
        return taskPointId;
    }

    public void setTaskPointId(String taskPointId) {
        this.taskPointId = taskPointId;
    }

    public String getHdType() {
        return hdType;
    }

    public void setHdType(String hdType) {
        this.hdType = hdType;
    }

    public String getHdDesc() {
        return hdDesc;
    }

    public void setHdDesc(String hdDesc) {
        this.hdDesc = hdDesc;
    }

    public Integer getRevInt1() {
        return revInt1;
    }

    public void setRevInt1(Integer revInt1) {
        this.revInt1 = revInt1;
    }

    public Integer getRevInt2() {
        return revInt2;
    }

    public void setRevInt2(Integer revInt2) {
        this.revInt2 = revInt2;
    }

    public String getRevString1() {
        return revString1;
    }

    public void setRevString1(String revString1) {
        this.revString1 = revString1;
    }

    public String getRevString2() {
        return revString2;
    }

    public void setRevString2(String revString2) {
        this.revString2 = revString2;
    }

}
