package com.yunwei.wetlandpark.greedao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SIGN_IN_TABLE".
 */
public class SignInTable implements java.io.Serializable {

    private Long id;
    private String userName;
    private String userID;
    private String code;
    private String address;
    private Double lng;
    private Double lat;
    private Long time;

    public SignInTable() {
    }

    public SignInTable(Long id) {
        this.id = id;
    }

    public SignInTable(Long id, String userName, String userID, String code, String address, Double lng, Double lat, Long time) {
        this.id = id;
        this.userName = userName;
        this.userID = userID;
        this.code = code;
        this.address = address;
        this.lng = lng;
        this.lat = lat;
        this.time = time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getUserID() {
        return userID;
    }

    public void setUserID(String userID) {
        this.userID = userID;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public Double getLng() {
        return lng;
    }

    public void setLng(Double lng) {
        this.lng = lng;
    }

    public Double getLat() {
        return lat;
    }

    public void setLat(Double lat) {
        this.lat = lat;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

}
