package com.yunwei.wetlandpark.greedao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TASK_POINT_LIST_ENTITY".
 */
public class TaskPointListEntity {

    private Long id;
    private Integer TaskId;
    private String TaskPointId;
    private Integer TaskPointKind;
    private Integer TaskPointStatus;
    private String UserId;
    private String TaskPointNo;
    private String TaskPointType;
    private String TaskPointAddr;
    private Double Lng;
    private Double Lat;
    private String Imgs;
    private Boolean IsCompleted;
    private Integer revint1;
    private Integer revint2;
    private Integer revint3;
    private String revstr1;
    private String revstr2;
    private String revstr3;

    public TaskPointListEntity() {
    }

    public TaskPointListEntity(Long id) {
        this.id = id;
    }

    public TaskPointListEntity(Long id, Integer TaskId, String TaskPointId, Integer TaskPointKind, Integer TaskPointStatus, String UserId, String TaskPointNo, String TaskPointType, String TaskPointAddr, Double Lng, Double Lat, String Imgs, Boolean IsCompleted, Integer revint1, Integer revint2, Integer revint3, String revstr1, String revstr2, String revstr3) {
        this.id = id;
        this.TaskId = TaskId;
        this.TaskPointId = TaskPointId;
        this.TaskPointKind = TaskPointKind;
        this.TaskPointStatus = TaskPointStatus;
        this.UserId = UserId;
        this.TaskPointNo = TaskPointNo;
        this.TaskPointType = TaskPointType;
        this.TaskPointAddr = TaskPointAddr;
        this.Lng = Lng;
        this.Lat = Lat;
        this.Imgs = Imgs;
        this.IsCompleted = IsCompleted;
        this.revint1 = revint1;
        this.revint2 = revint2;
        this.revint3 = revint3;
        this.revstr1 = revstr1;
        this.revstr2 = revstr2;
        this.revstr3 = revstr3;
    }

    public Long getId() {
        return id;
    }

    public TaskPointListEntity setId(Long id) {
        this.id = id;
        return this;
    }

    public Integer getTaskId() {
        return TaskId;
    }

    public TaskPointListEntity setTaskId(Integer taskId) {
        TaskId = taskId;
        return this;
    }

    public String getTaskPointId() {
        return TaskPointId;
    }

    public TaskPointListEntity setTaskPointId(String taskPointId) {
        TaskPointId = taskPointId;
        return this;
    }

    public Integer getTaskPointKind() {
        return TaskPointKind;
    }

    public TaskPointListEntity setTaskPointKind(Integer taskPointKind) {
        TaskPointKind = taskPointKind;
        return this;
    }

    public Integer getTaskPointStatus() {
        return TaskPointStatus;
    }

    public TaskPointListEntity setTaskPointStatus(Integer taskPointStatus) {
        TaskPointStatus = taskPointStatus;
        return this;
    }

    public String getUserId() {
        return UserId;
    }

    public TaskPointListEntity setUserId(String userId) {
        UserId = userId;
        return this;
    }

    public String getTaskPointNo() {
        return TaskPointNo;
    }

    public TaskPointListEntity setTaskPointNo(String taskPointNo) {
        TaskPointNo = taskPointNo;
        return this;
    }

    public String getTaskPointType() {
        return TaskPointType;
    }

    public TaskPointListEntity setTaskPointType(String taskPointType) {
        TaskPointType = taskPointType;
        return this;
    }

    public String getTaskPointAddr() {
        return TaskPointAddr;
    }

    public TaskPointListEntity setTaskPointAddr(String taskPointAddr) {
        TaskPointAddr = taskPointAddr;
        return this;
    }

    public Double getLng() {
        return Lng;
    }

    public TaskPointListEntity setLng(Double lng) {
        Lng = lng;
        return this;
    }

    public Double getLat() {
        return Lat;
    }

    public TaskPointListEntity setLat(Double lat) {
        Lat = lat;
        return this;
    }

    public String getImgs() {
        return Imgs;
    }

    public TaskPointListEntity setImgs(String imgs) {
        Imgs = imgs;
        return this;
    }

    public Boolean getCompleted() {
        return IsCompleted;
    }

    public TaskPointListEntity setCompleted(Boolean completed) {
        IsCompleted = completed;
        return this;
    }

    public Integer getRevint1() {
        return revint1;
    }

    public TaskPointListEntity setRevint1(Integer revint1) {
        this.revint1 = revint1;
        return this;
    }

    public Integer getRevint2() {
        return revint2;
    }

    public TaskPointListEntity setRevint2(Integer revint2) {
        this.revint2 = revint2;
        return this;
    }

    public Integer getRevint3() {
        return revint3;
    }

    public TaskPointListEntity setRevint3(Integer revint3) {
        this.revint3 = revint3;
        return this;
    }

    public String getRevstr1() {
        return revstr1;
    }

    public TaskPointListEntity setRevstr1(String revstr1) {
        this.revstr1 = revstr1;
        return this;
    }

    public String getRevstr2() {
        return revstr2;
    }

    public TaskPointListEntity setRevstr2(String revstr2) {
        this.revstr2 = revstr2;
        return this;
    }

    public String getRevstr3() {
        return revstr3;
    }

    public TaskPointListEntity setRevstr3(String revstr3) {
        this.revstr3 = revstr3;
        return this;
    }

    public String getTaskPointKindString(int taskPointKind) {
        switch (taskPointKind) {
            //临时点
            case 0:
                return "临时点";
            //设施
            case 1:
                return "设施";
            //隐患
            case 2:
                return "隐患";
        }
        return "";
    }

}
