package com.yunwei.wetlandpark.greedao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TRACK_POINT".
 */
public class TrackPoint implements java.io.Serializable {

    private Long id;
    private Long pId;
    private Long time;
    private Double lat;
    private Double lng;
    private Double x;
    private Double y;
    private Float speed;
    private Float gpsSpeed;
    private Double distance;
    private String provider;
    private String locationMode;
    private String address;
    private Integer revint1;
    private Integer revint2;
    private Integer revint3;
    private String revstr1;
    private String revstr2;
    private String revstr3;

    public TrackPoint() {
    }

    public TrackPoint(Long id) {
        this.id = id;
    }

    public TrackPoint(Long id, Long pId, Long time, Double lat, Double lng, Double x, Double y, Float speed, Float gpsSpeed, Double distance, String provider, String locationMode, String address, Integer revint1, Integer revint2, Integer revint3, String revstr1, String revstr2, String revstr3) {
        this.id = id;
        this.pId = pId;
        this.time = time;
        this.lat = lat;
        this.lng = lng;
        this.x = x;
        this.y = y;
        this.speed = speed;
        this.gpsSpeed = gpsSpeed;
        this.distance = distance;
        this.provider = provider;
        this.locationMode = locationMode;
        this.address = address;
        this.revint1 = revint1;
        this.revint2 = revint2;
        this.revint3 = revint3;
        this.revstr1 = revstr1;
        this.revstr2 = revstr2;
        this.revstr3 = revstr3;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getPId() {
        return pId;
    }

    public void setPId(Long pId) {
        this.pId = pId;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

    public Double getLat() {
        return lat;
    }

    public void setLat(Double lat) {
        this.lat = lat;
    }

    public Double getLng() {
        return lng;
    }

    public void setLng(Double lng) {
        this.lng = lng;
    }

    public Double getX() {
        return x;
    }

    public void setX(Double x) {
        this.x = x;
    }

    public Double getY() {
        return y;
    }

    public void setY(Double y) {
        this.y = y;
    }

    public Float getSpeed() {
        return speed;
    }

    public void setSpeed(Float speed) {
        this.speed = speed;
    }

    public Float getGpsSpeed() {
        return gpsSpeed;
    }

    public void setGpsSpeed(Float gpsSpeed) {
        this.gpsSpeed = gpsSpeed;
    }

    public Double getDistance() {
        return distance;
    }

    public void setDistance(Double distance) {
        this.distance = distance;
    }

    public String getProvider() {
        return provider;
    }

    public void setProvider(String provider) {
        this.provider = provider;
    }

    public String getLocationMode() {
        return locationMode;
    }

    public void setLocationMode(String locationMode) {
        this.locationMode = locationMode;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public Integer getRevint1() {
        return revint1;
    }

    public void setRevint1(Integer revint1) {
        this.revint1 = revint1;
    }

    public Integer getRevint2() {
        return revint2;
    }

    public void setRevint2(Integer revint2) {
        this.revint2 = revint2;
    }

    public Integer getRevint3() {
        return revint3;
    }

    public void setRevint3(Integer revint3) {
        this.revint3 = revint3;
    }

    public String getRevstr1() {
        return revstr1;
    }

    public void setRevstr1(String revstr1) {
        this.revstr1 = revstr1;
    }

    public String getRevstr2() {
        return revstr2;
    }

    public void setRevstr2(String revstr2) {
        this.revstr2 = revstr2;
    }

    public String getRevstr3() {
        return revstr3;
    }

    public void setRevstr3(String revstr3) {
        this.revstr3 = revstr3;
    }

}
