package com.yunwei.wetlandpark.greedao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TRACK".
 */
public class Track implements java.io.Serializable {

    private Long id;
    private Long tId;
    private Long startTime;
    private Long endTime;
    private Double distance;
    private Integer state;
    private String remark;
    private String resume;
    private String pause;
    private Integer revint1;
    private Integer revint2;
    private Integer revint3;
    private String revstr1;
    private String revstr2;
    private String revstr3;

    public Track() {
    }

    public Track(Long id) {
        this.id = id;
    }

    public Track(Long id, Long tId, Long startTime, Long endTime, Double distance, Integer state, String remark, String resume, String pause, Integer revint1, Integer revint2, Integer revint3, String revstr1, String revstr2, String revstr3) {
        this.id = id;
        this.tId = tId;
        this.startTime = startTime;
        this.endTime = endTime;
        this.distance = distance;
        this.state = state;
        this.remark = remark;
        this.resume = resume;
        this.pause = pause;
        this.revint1 = revint1;
        this.revint2 = revint2;
        this.revint3 = revint3;
        this.revstr1 = revstr1;
        this.revstr2 = revstr2;
        this.revstr3 = revstr3;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getTId() {
        return tId;
    }

    public void setTId(Long tId) {
        this.tId = tId;
    }

    public Long getStartTime() {
        return startTime;
    }

    public void setStartTime(Long startTime) {
        this.startTime = startTime;
    }

    public Long getEndTime() {
        return endTime;
    }

    public void setEndTime(Long endTime) {
        this.endTime = endTime;
    }

    public Double getDistance() {
        return distance;
    }

    public void setDistance(Double distance) {
        this.distance = distance;
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getResume() {
        return resume;
    }

    public void setResume(String resume) {
        this.resume = resume;
    }

    public String getPause() {
        return pause;
    }

    public void setPause(String pause) {
        this.pause = pause;
    }

    public Integer getRevint1() {
        return revint1;
    }

    public void setRevint1(Integer revint1) {
        this.revint1 = revint1;
    }

    public Integer getRevint2() {
        return revint2;
    }

    public void setRevint2(Integer revint2) {
        this.revint2 = revint2;
    }

    public Integer getRevint3() {
        return revint3;
    }

    public void setRevint3(Integer revint3) {
        this.revint3 = revint3;
    }

    public String getRevstr1() {
        return revstr1;
    }

    public void setRevstr1(String revstr1) {
        this.revstr1 = revstr1;
    }

    public String getRevstr2() {
        return revstr2;
    }

    public void setRevstr2(String revstr2) {
        this.revstr2 = revstr2;
    }

    public String getRevstr3() {
        return revstr3;
    }

    public void setRevstr3(String revstr3) {
        this.revstr3 = revstr3;
    }

}
