package com.yunwei.wetlandpark.greedao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.yunwei.wetlandpark.greedao.TroubleShooterTable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TROUBLE_SHOOTER_TABLE".
*/
public class TroubleShooterTableDao extends AbstractDao<TroubleShooterTable, Long> {

    public static final String TABLENAME = "TROUBLE_SHOOTER_TABLE";

    /**
     * Properties of entity TroubleShooterTable.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UserName = new Property(1, String.class, "userName", false, "USER_NAME");
        public final static Property UserID = new Property(2, String.class, "userID", false, "USER_ID");
        public final static Property TroubleID = new Property(3, String.class, "troubleID", false, "TROUBLE_ID");
        public final static Property MissionDetailID = new Property(4, String.class, "missionDetailID", false, "MISSION_DETAIL_ID");
        public final static Property MissionID = new Property(5, String.class, "missionID", false, "MISSION_ID");
        public final static Property Lng = new Property(6, Double.class, "lng", false, "LNG");
        public final static Property Lat = new Property(7, Double.class, "lat", false, "LAT");
        public final static Property Time = new Property(8, Long.class, "time", false, "TIME");
        public final static Property Note = new Property(9, String.class, "note", false, "NOTE");
        public final static Property ImagesUrl = new Property(10, String.class, "imagesUrl", false, "IMAGES_URL");
        public final static Property LocalTag = new Property(11, Integer.class, "localTag", false, "LOCAL_TAG");
    };


    public TroubleShooterTableDao(DaoConfig config) {
        super(config);
    }
    
    public TroubleShooterTableDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TROUBLE_SHOOTER_TABLE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"USER_NAME\" TEXT," + // 1: userName
                "\"USER_ID\" TEXT," + // 2: userID
                "\"TROUBLE_ID\" TEXT," + // 3: troubleID
                "\"MISSION_DETAIL_ID\" TEXT," + // 4: missionDetailID
                "\"MISSION_ID\" TEXT," + // 5: missionID
                "\"LNG\" REAL," + // 6: lng
                "\"LAT\" REAL," + // 7: lat
                "\"TIME\" INTEGER," + // 8: time
                "\"NOTE\" TEXT," + // 9: note
                "\"IMAGES_URL\" TEXT," + // 10: imagesUrl
                "\"LOCAL_TAG\" INTEGER);"); // 11: localTag
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TROUBLE_SHOOTER_TABLE\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, TroubleShooterTable entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String userName = entity.getUserName();
        if (userName != null) {
            stmt.bindString(2, userName);
        }
 
        String userID = entity.getUserID();
        if (userID != null) {
            stmt.bindString(3, userID);
        }
 
        String troubleID = entity.getTroubleID();
        if (troubleID != null) {
            stmt.bindString(4, troubleID);
        }
 
        String missionDetailID = entity.getMissionDetailID();
        if (missionDetailID != null) {
            stmt.bindString(5, missionDetailID);
        }
 
        String missionID = entity.getMissionID();
        if (missionID != null) {
            stmt.bindString(6, missionID);
        }
 
        Double lng = entity.getLng();
        if (lng != null) {
            stmt.bindDouble(7, lng);
        }
 
        Double lat = entity.getLat();
        if (lat != null) {
            stmt.bindDouble(8, lat);
        }
 
        Long time = entity.getTime();
        if (time != null) {
            stmt.bindLong(9, time);
        }
 
        String note = entity.getNote();
        if (note != null) {
            stmt.bindString(10, note);
        }
 
        String imagesUrl = entity.getImagesUrl();
        if (imagesUrl != null) {
            stmt.bindString(11, imagesUrl);
        }
 
        Integer localTag = entity.getLocalTag();
        if (localTag != null) {
            stmt.bindLong(12, localTag);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public TroubleShooterTable readEntity(Cursor cursor, int offset) {
        TroubleShooterTable entity = new TroubleShooterTable( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // userName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // userID
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // troubleID
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // missionDetailID
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // missionID
            cursor.isNull(offset + 6) ? null : cursor.getDouble(offset + 6), // lng
            cursor.isNull(offset + 7) ? null : cursor.getDouble(offset + 7), // lat
            cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8), // time
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // note
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // imagesUrl
            cursor.isNull(offset + 11) ? null : cursor.getInt(offset + 11) // localTag
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, TroubleShooterTable entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setUserID(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTroubleID(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setMissionDetailID(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setMissionID(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setLng(cursor.isNull(offset + 6) ? null : cursor.getDouble(offset + 6));
        entity.setLat(cursor.isNull(offset + 7) ? null : cursor.getDouble(offset + 7));
        entity.setTime(cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8));
        entity.setNote(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setImagesUrl(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setLocalTag(cursor.isNull(offset + 11) ? null : cursor.getInt(offset + 11));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(TroubleShooterTable entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(TroubleShooterTable entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
