package com.yunwei.wetlandpark.greedao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TROUBLE_SHOOTER_TABLE".
 */
public class TroubleShooterTable implements java.io.Serializable {

    private Long id;
    private String userName;
    private String userID;
    private String troubleID;
    private String missionDetailID;
    private String missionID;
    private Double lng;
    private Double lat;
    private Long time;
    private String note;
    private String imagesUrl;
    private Integer localTag;

    public TroubleShooterTable() {
    }

    public TroubleShooterTable(Long id) {
        this.id = id;
    }

    public TroubleShooterTable(Long id, String userName, String userID, String troubleID, String missionDetailID, String missionID, Double lng, Double lat, Long time, String note, String imagesUrl, Integer localTag) {
        this.id = id;
        this.userName = userName;
        this.userID = userID;
        this.troubleID = troubleID;
        this.missionDetailID = missionDetailID;
        this.missionID = missionID;
        this.lng = lng;
        this.lat = lat;
        this.time = time;
        this.note = note;
        this.imagesUrl = imagesUrl;
        this.localTag = localTag;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getUserID() {
        return userID;
    }

    public void setUserID(String userID) {
        this.userID = userID;
    }

    public String getTroubleID() {
        return troubleID;
    }

    public void setTroubleID(String troubleID) {
        this.troubleID = troubleID;
    }

    public String getMissionDetailID() {
        return missionDetailID;
    }

    public void setMissionDetailID(String missionDetailID) {
        this.missionDetailID = missionDetailID;
    }

    public String getMissionID() {
        return missionID;
    }

    public void setMissionID(String missionID) {
        this.missionID = missionID;
    }

    public Double getLng() {
        return lng;
    }

    public void setLng(Double lng) {
        this.lng = lng;
    }

    public Double getLat() {
        return lat;
    }

    public void setLat(Double lat) {
        this.lat = lat;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

    public String getNote() {
        return note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    public String getImagesUrl() {
        return imagesUrl;
    }

    public void setImagesUrl(String imagesUrl) {
        this.imagesUrl = imagesUrl;
    }

    public Integer getLocalTag() {
        return localTag;
    }

    public void setLocalTag(Integer localTag) {
        this.localTag = localTag;
    }

}
