package com.yunwei.wetlandpark.greedao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TROUBLE_TABLE".
 */
public class TroubleTable implements java.io.Serializable {

    private Long id;
    private String userName;
    private String userID;
    private String troubleType;
    private String troubleDesc;
    private Double lng;
    private Double lat;
    private String troubleAddress;
    private Long time;
    private String note;
    private String imagesUrl;
    private Integer localTag;
    private Integer emergencyLevel;
    private String missionID;
    private String missionPointID;

    public TroubleTable() {
    }

    public TroubleTable(Long id) {
        this.id = id;
    }

    public TroubleTable(Long id, String userName, String userID, String troubleType, String troubleDesc, Double lng, Double lat, String troubleAddress, Long time, String note, String imagesUrl, Integer localTag, Integer emergencyLevel, String missionID, String missionPointID) {
        this.id = id;
        this.userName = userName;
        this.userID = userID;
        this.troubleType = troubleType;
        this.troubleDesc = troubleDesc;
        this.lng = lng;
        this.lat = lat;
        this.troubleAddress = troubleAddress;
        this.time = time;
        this.note = note;
        this.imagesUrl = imagesUrl;
        this.localTag = localTag;
        this.emergencyLevel = emergencyLevel;
        this.missionID = missionID;
        this.missionPointID = missionPointID;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getUserID() {
        return userID;
    }

    public void setUserID(String userID) {
        this.userID = userID;
    }

    public String getTroubleType() {
        return troubleType;
    }

    public void setTroubleType(String troubleType) {
        this.troubleType = troubleType;
    }

    public String getTroubleDesc() {
        return troubleDesc;
    }

    public void setTroubleDesc(String troubleDesc) {
        this.troubleDesc = troubleDesc;
    }

    public Double getLng() {
        return lng;
    }

    public void setLng(Double lng) {
        this.lng = lng;
    }

    public Double getLat() {
        return lat;
    }

    public void setLat(Double lat) {
        this.lat = lat;
    }

    public String getTroubleAddress() {
        return troubleAddress;
    }

    public void setTroubleAddress(String troubleAddress) {
        this.troubleAddress = troubleAddress;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

    public String getNote() {
        return note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    public String getImagesUrl() {
        return imagesUrl;
    }

    public void setImagesUrl(String imagesUrl) {
        this.imagesUrl = imagesUrl;
    }

    public Integer getLocalTag() {
        return localTag;
    }

    public void setLocalTag(Integer localTag) {
        this.localTag = localTag;
    }

    public Integer getEmergencyLevel() {
        return emergencyLevel;
    }

    public void setEmergencyLevel(Integer emergencyLevel) {
        this.emergencyLevel = emergencyLevel;
    }

    public String getMissionID() {
        return missionID;
    }

    public void setMissionID(String missionID) {
        this.missionID = missionID;
    }

    public String getMissionPointID() {
        return missionPointID;
    }

    public void setMissionPointID(String missionPointID) {
        this.missionPointID = missionPointID;
    }

}
