package com.yunwei.wetlandpark.greedao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "WORK_RECORD_TABLE".
 */
public class WorkRecordTable implements java.io.Serializable {

    private Long id;
    private String taskID;
    private String taskPointID;
    private String deviceType;
    private String deviceCode;
    private String deviceID;
    private String roadLocation;
    private String areaLocation;
    private String remark;
    private Integer recordType;
    private Integer useState;
    private Integer localTag;
    private Double lng;
    private Double lat;
    private String address;
    private String workAddress;
    private Long saveTime;
    private String userName;
    private String userID;
    private String workDesc;
    private String faultReason;
    private String reportType;
    private String hdType;
    private String hdDesc;
    private String imagesUrl;
    private String reservedStringOne;
    private String reservedStringTow;
    private Integer reservedIntOne;

    public WorkRecordTable() {
    }

    public WorkRecordTable(Long id) {
        this.id = id;
    }

    public WorkRecordTable(Long id, String taskID, String taskPointID, String deviceType, String deviceCode, String deviceID, String roadLocation, String areaLocation, String remark, Integer recordType, Integer useState, Integer localTag, Double lng, Double lat, String address, String workAddress, Long saveTime, String userName, String userID, String workDesc, String faultReason, String reportType, String hdType, String hdDesc, String imagesUrl, String reservedStringOne, String reservedStringTow, Integer reservedIntOne) {
        this.id = id;
        this.taskID = taskID;
        this.taskPointID = taskPointID;
        this.deviceType = deviceType;
        this.deviceCode = deviceCode;
        this.deviceID = deviceID;
        this.roadLocation = roadLocation;
        this.areaLocation = areaLocation;
        this.remark = remark;
        this.recordType = recordType;
        this.useState = useState;
        this.localTag = localTag;
        this.lng = lng;
        this.lat = lat;
        this.address = address;
        this.workAddress = workAddress;
        this.saveTime = saveTime;
        this.userName = userName;
        this.userID = userID;
        this.workDesc = workDesc;
        this.faultReason = faultReason;
        this.reportType = reportType;
        this.hdType = hdType;
        this.hdDesc = hdDesc;
        this.imagesUrl = imagesUrl;
        this.reservedStringOne = reservedStringOne;
        this.reservedStringTow = reservedStringTow;
        this.reservedIntOne = reservedIntOne;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTaskID() {
        return taskID;
    }

    public void setTaskID(String taskID) {
        this.taskID = taskID;
    }

    public String getTaskPointID() {
        return taskPointID;
    }

    public void setTaskPointID(String taskPointID) {
        this.taskPointID = taskPointID;
    }

    public String getDeviceType() {
        return deviceType;
    }

    public void setDeviceType(String deviceType) {
        this.deviceType = deviceType;
    }

    public String getDeviceCode() {
        return deviceCode;
    }

    public void setDeviceCode(String deviceCode) {
        this.deviceCode = deviceCode;
    }

    public String getDeviceID() {
        return deviceID;
    }

    public void setDeviceID(String deviceID) {
        this.deviceID = deviceID;
    }

    public String getRoadLocation() {
        return roadLocation;
    }

    public void setRoadLocation(String roadLocation) {
        this.roadLocation = roadLocation;
    }

    public String getAreaLocation() {
        return areaLocation;
    }

    public void setAreaLocation(String areaLocation) {
        this.areaLocation = areaLocation;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public Integer getRecordType() {
        return recordType;
    }

    public void setRecordType(Integer recordType) {
        this.recordType = recordType;
    }

    public Integer getUseState() {
        return useState;
    }

    public void setUseState(Integer useState) {
        this.useState = useState;
    }

    public Integer getLocalTag() {
        return localTag;
    }

    public void setLocalTag(Integer localTag) {
        this.localTag = localTag;
    }

    public Double getLng() {
        return lng;
    }

    public void setLng(Double lng) {
        this.lng = lng;
    }

    public Double getLat() {
        return lat;
    }

    public void setLat(Double lat) {
        this.lat = lat;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getWorkAddress() {
        return workAddress;
    }

    public void setWorkAddress(String workAddress) {
        this.workAddress = workAddress;
    }

    public Long getSaveTime() {
        return saveTime;
    }

    public void setSaveTime(Long saveTime) {
        this.saveTime = saveTime;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getUserID() {
        return userID;
    }

    public void setUserID(String userID) {
        this.userID = userID;
    }

    public String getWorkDesc() {
        return workDesc;
    }

    public void setWorkDesc(String workDesc) {
        this.workDesc = workDesc;
    }

    public String getFaultReason() {
        return faultReason;
    }

    public void setFaultReason(String faultReason) {
        this.faultReason = faultReason;
    }

    public String getReportType() {
        return reportType;
    }

    public void setReportType(String reportType) {
        this.reportType = reportType;
    }

    public String getHdType() {
        return hdType;
    }

    public void setHdType(String hdType) {
        this.hdType = hdType;
    }

    public String getHdDesc() {
        return hdDesc;
    }

    public void setHdDesc(String hdDesc) {
        this.hdDesc = hdDesc;
    }

    public String getImagesUrl() {
        return imagesUrl;
    }

    public void setImagesUrl(String imagesUrl) {
        this.imagesUrl = imagesUrl;
    }

    public String getReservedStringOne() {
        return reservedStringOne;
    }

    public void setReservedStringOne(String reservedStringOne) {
        this.reservedStringOne = reservedStringOne;
    }

    public String getReservedStringTow() {
        return reservedStringTow;
    }

    public void setReservedStringTow(String reservedStringTow) {
        this.reservedStringTow = reservedStringTow;
    }

    public Integer getReservedIntOne() {
        return reservedIntOne;
    }

    public void setReservedIntOne(Integer reservedIntOne) {
        this.reservedIntOne = reservedIntOne;
    }

}
